### ISSUE TITLE
ERD design

### ISSUE THREAD

**Issue by khanshakeeb** [khanshakeeb/wad18_ae_bidding_site#2]
Design ERD diagram and share with everyone

**Comment by danishyounus12** [comment]
![erd relationship diagram](https://user-images.githubusercontent.com/44539655/47705080-53b59d00-dc47-11e8-81c8-d82e79fca6a2.png)
![erd diagram](https://user-images.githubusercontent.com/44539655/47705081-53b59d00-dc47-11e8-8819-4a4cf63f77f5.png)

**Comment by khanshakeeb** [comment]
@danishyounus12 you only need to correct columns name e.g 

u_id should "uid"
user_name should "username"
roles_names should be "name" 

in table "product_type" foreign key should be "project_id"
and same for other table. Just remember the name foreign key should be table name prefix and id.
e.g foreign key should = <table_name_id>

**Comment by danishyounus12** [comment]
![erdplus-diagram](https://user-images.githubusercontent.com/44539655/47730457-00157480-dc84-11e8-8316-31b14463bee9.png)
![erdplus-diagram 1](https://user-images.githubusercontent.com/44539655/47730458-00157480-dc84-11e8-8d84-f91423369273.png)
Sir @khanshakeeb, if i am doing any mistake again, kindly correct me.

**Comment by Shahf172** [comment]
ERD Diagram Sir Kindly Check this And Correct if i am wrong
![entity_relation_diagram](https://user-images.githubusercontent.com/28339853/47740124-d7e44080-dc98-11e8-9dd8-399cbb1e7c8e.png)

**Comment by khanshakeeb** [comment]
@Shahf172 
payment type/user payment table i dont understand over all looks good but we have to finalize one ERD version so developers will not confused. I believe you both sit together and draft a final version both are using different approach in field names. 

@danishyounus12 
projects_id should be project_id (should be singular field name)

**Comment by Shahf172** [comment]
Payment type is for ongoing type and one time payment and user_payment is representing payment table by mistake I wrote user_payment. And I can't sit with him sir because of job late sitting issues

**Comment by khanshakeeb** [comment]
@Shahf172  Ok, then we have to finalize on ERD either yours or either @danishyounus12 warna it will be confusion which ERD we need to follow.

Thanks

**Comment by khanshakeeb** [comment]
You guys can communicate over slack infact in #general channel that is why I have created slack would be easier. Lets discuss there more quickly we will decide
