### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by khanshakeeb** [khanshakeeb/wad18_ae_bidding_site#4]
After receiving mockup we need to write html/css for the mockups

1. home page
2. listing page
3. detail page
4. admin panel screens
5. login/signup page/popup
6. Search pages
7. Static pages e.g about  us, contact us etc...
8. CRUD pages

Please comment on this ticket those are working on mockups part for the project.

**Comment by khanshakeeb** [comment]
Guys when this mockup will be done so that html/css can be done

**Comment by devtram** [comment]
Sir, please confirm do we need the mockups as slices and so on? Thanks!

**Comment by khanshakeeb** [comment]
@titanscomputer no as we are not going to create layered PSD. I believe we should quickly draft mockup so that our html/css developers will be easier to follow one guideline otherwise they will be confuse which design need to follow

**Comment by devtram** [comment]
Got it we'll work together to attach Sample PSD mockups but not layered hopefully tomorrow. Thanks

**Comment by devtram** [comment]
Homepage is ready in collaboration with Faizullah for to work on UI.

![homepage](https://user-images.githubusercontent.com/9325827/47806791-58b84080-dd5c-11e8-8642-707c61c5e311.jpg)

**Comment by devtram** [comment]
![homepage3](https://user-images.githubusercontent.com/9325827/47817492-89f23a00-dd77-11e8-98bb-57d60c5b96e6.jpg)

Final Mockup for homepage and rest will use this layout. Thanks

**Comment by UsmanSaghri** [comment]
Got it

**Comment by devtram** [comment]
@UsmanSaghri  Please use this jpg to create, Project Details page, where bids will appear and project description. Thanks!
![page](https://user-images.githubusercontent.com/9325827/47838211-6f987a80-ddd0-11e8-9ab5-afad63754442.jpg)

**Comment by devtram** [comment]
Listing Page Finished
![listing page](https://user-images.githubusercontent.com/9325827/47847792-25be8d00-ddee-11e8-968f-f76ee3ec4c2b.jpg)

**Comment by devtram** [comment]
![details](https://user-images.githubusercontent.com/9325827/47871672-82419c80-de2e-11e8-9a1e-844bd2d35301.jpg)

Details Page (Seller End Finished) I think we need a similar for Buyer's end.

**Comment by devtram** [comment]
I think search page will be part of Listing page so I think it's also done

**Comment by khanshakeeb** [comment]
All right are we going to keep same colors? Or you guys will change it later?

**Comment by khanshakeeb** [comment]
Great job guys it seems you are moving quickly as compare to saturday class

**Comment by devtram** [comment]
Thanks Sir, I think we'll keep yellow and dark purple

**Comment by Faizullahshah** [comment]
![home page](https://user-images.githubusercontent.com/44539677/47948318-d9d82900-df50-11e8-8d3a-b1c6ab7600d2.jpg)

**Comment by Faizullahshah** [comment]
![listing](https://user-images.githubusercontent.com/44539677/47948336-0ee47b80-df51-11e8-8ebb-f149dca5ee75.jpg)

**Comment by devtram** [comment]
![image](https://user-images.githubusercontent.com/9325827/47949897-3563e000-df6c-11e8-9282-6762266f5baf.png)
![image](https://user-images.githubusercontent.com/9325827/47949900-3eed4800-df6c-11e8-820f-169e48836c3b.png)
![image](https://user-images.githubusercontent.com/9325827/47949901-41e83880-df6c-11e8-9661-0d9d4846bf4b.png)
![image](https://user-images.githubusercontent.com/9325827/47949902-46145600-df6c-11e8-92d0-095122d7b349.png)
